"""Workflows: immutable versions, deployment history, durable executions and steps.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 02:14:19.373937
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import solutionforge.db.base

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STEPS_NO_UPDATE_FN = """
CREATE OR REPLACE FUNCTION execution_steps_reject_update() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'execution_steps rows are immutable (UPDATE rejected)'
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_workflows_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflows_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_workflows_organization_id_name")
        ),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflows_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "workflow_versions",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "definition", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("changelog", sa.String(length=2000), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_workflow_versions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_versions_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint(
            "workflow_id", "version", name=op.f("uq_workflow_versions_workflow_id_version")
        ),
    )
    with op.batch_alter_table("workflow_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_versions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_versions_workflow_id"), ["workflow_id"], unique=False
        )

    op.create_table(
        "executions",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "waiting",
                "succeeded",
                "failed",
                "cancelled",
                "budget_exceeded",
                name="execution_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "input", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "state", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "step_outputs", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("error", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column(
            "waiting_on", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("current_attempt", sa.Integer(), nullable=False),
        sa.Column("steps_used", sa.Integer(), nullable=False),
        sa.Column("active_ms", sa.Integer(), nullable=False),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("run_after", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column(
            "lease_expires_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("started_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_executions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_executions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_executions_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_executions_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_executions_organization_id_idempotency_key"),
        ),
    )
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.create_index("ix_executions_claim", ["status", "run_after"], unique=False)
        batch_op.create_index(
            "ix_executions_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_executions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_executions_workflow_id"), ["workflow_id"], unique=False
        )

    op.create_table(
        "workflow_deployments",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("deployed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployed_by_user_id"],
            ["users.id"],
            name=op.f("fk_workflow_deployments_deployed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_deployments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_deployments_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_deployments_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_deployments")),
    )
    with op.batch_alter_table("workflow_deployments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_deployments_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_workflow_deployments_wf_created", ["workflow_id", "created_at"], unique=False
        )

    op.create_table(
        "execution_steps",
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("step_type", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded",
                "failed",
                "waiting",
                "resumed",
                name="step_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("worker_id", sa.String(length=64), nullable=True),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("error", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("started_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_execution_steps_execution_id_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_execution_steps_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_steps")),
        sa.UniqueConstraint(
            "execution_id", "seq", name=op.f("uq_execution_steps_execution_id_seq")
        ),
    )
    with op.batch_alter_table("execution_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_execution_steps_execution_id"), ["execution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_steps_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # Step history is the execution's evidence trail: rows are written once, never edited.
        # DELETE stays allowed so organization deletion can cascade.
        op.execute(_STEPS_NO_UPDATE_FN)
        op.execute(
            "CREATE TRIGGER execution_steps_immutable BEFORE UPDATE ON execution_steps "
            "FOR EACH ROW EXECUTE FUNCTION execution_steps_reject_update()"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS execution_steps_immutable ON execution_steps")
        op.execute("DROP FUNCTION IF EXISTS execution_steps_reject_update()")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execution_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_steps_organization_id"))
        batch_op.drop_index(batch_op.f("ix_execution_steps_execution_id"))

    op.drop_table("execution_steps")
    with op.batch_alter_table("workflow_deployments", schema=None) as batch_op:
        batch_op.drop_index("ix_workflow_deployments_wf_created")
        batch_op.drop_index(batch_op.f("ix_workflow_deployments_organization_id"))

    op.drop_table("workflow_deployments")
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executions_workflow_id"))
        batch_op.drop_index(batch_op.f("ix_executions_organization_id"))
        batch_op.drop_index("ix_executions_org_created")
        batch_op.drop_index("ix_executions_claim")

    op.drop_table("executions")
    with op.batch_alter_table("workflow_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_versions_workflow_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_versions_organization_id"))

    op.drop_table("workflow_versions")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflows_organization_id"))

    op.drop_table("workflows")
    # ### end Alembic commands ###
