"""LLM usage ledger (every provider attempt, micro-USD) and per-organization budgets.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 02:41:35.057316
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import solutionforge.db.base

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_budgets",
        sa.Column("daily_limit_micro_usd", sa.BigInteger(), nullable=True),
        sa.Column("monthly_limit_micro_usd", sa.BigInteger(), nullable=True),
        sa.Column("per_execution_limit_micro_usd", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_org_budgets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_org_budgets_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_budgets")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_org_budgets_organization_id")),
    )
    with op.batch_alter_table("org_budgets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_org_budgets_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "usage_records",
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("step_id", sa.String(length=64), nullable=True),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=96), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_micro_usd", sa.BigInteger(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("fallback_index", sa.Integer(), nullable=False),
        sa.Column("provider_request_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_records_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.create_index("ix_usage_records_execution", ["execution_id"], unique=False)
        batch_op.create_index(
            "ix_usage_records_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usage_records_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_records_organization_id"))
        batch_op.drop_index("ix_usage_records_org_created")
        batch_op.drop_index("ix_usage_records_execution")

    op.drop_table("usage_records")
    with op.batch_alter_table("org_budgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_budgets_organization_id"))

    op.drop_table("org_budgets")
    # ### end Alembic commands ###
