"""Tools: installations (encrypted credentials), tool-call trail, simulated systems, visit_seq.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 03:15:57.382946
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import solutionforge.db.base

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sim_customers",
        sa.Column("ref", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("account_status", sa.String(length=16), nullable=False),
        sa.Column("lifetime_value_cents", sa.BigInteger(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sim_customers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_customers")),
        sa.UniqueConstraint(
            "organization_id", "ref", name=op.f("uq_sim_customers_organization_id_ref")
        ),
    )
    with op.batch_alter_table("sim_customers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sim_customers_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "sim_messages",
        sa.Column("to_address", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("sent_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sim_messages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_messages")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_sim_messages_organization_id_idempotency_key"),
        ),
    )
    with op.batch_alter_table("sim_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sim_messages_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "tool_calls",
        sa.Column("tool_name", sa.String(length=96), nullable=False),
        sa.Column("risk_level", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("step_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("args", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("error", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tool_calls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint(
            "organization_id",
            "tool_name",
            "idempotency_key",
            name=op.f("uq_tool_calls_organization_id_tool_name_idempotency_key"),
        ),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index("ix_tool_calls_execution", ["execution_id"], unique=False)
        batch_op.create_index(
            "ix_tool_calls_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tool_calls_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "tool_installations",
        sa.Column("tool_name", sa.String(length=96), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_approve_low_risk", sa.Boolean(), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("credentials_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tool_installations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_tool_installations_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_installations")),
        sa.UniqueConstraint(
            "organization_id",
            "tool_name",
            name=op.f("uq_tool_installations_organization_id_tool_name"),
        ),
    )
    with op.batch_alter_table("tool_installations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tool_installations_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "sim_orders",
        sa.Column("ref", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("promised_date", sa.Date(), nullable=False),
        sa.Column("delivered_date", sa.Date(), nullable=True),
        sa.Column("delay_reason", sa.String(length=200), nullable=True),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["sim_customers.id"],
            name=op.f("fk_sim_orders_customer_id_sim_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sim_orders_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_orders")),
        sa.UniqueConstraint(
            "organization_id", "ref", name=op.f("uq_sim_orders_organization_id_ref")
        ),
    )
    with op.batch_alter_table("sim_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sim_orders_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sim_orders_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "sim_tickets",
        sa.Column("ref", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["sim_customers.id"],
            name=op.f("fk_sim_tickets_customer_id_sim_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sim_tickets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_tickets")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_sim_tickets_organization_id_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "organization_id", "ref", name=op.f("uq_sim_tickets_organization_id_ref")
        ),
    )
    with op.batch_alter_table("sim_tickets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sim_tickets_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "sim_refunds",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sim_orders.id"],
            name=op.f("fk_sim_refunds_order_id_sim_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sim_refunds_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_refunds")),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            name=op.f("uq_sim_refunds_organization_id_idempotency_key"),
        ),
    )
    with op.batch_alter_table("sim_refunds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sim_refunds_organization_id"), ["organization_id"], unique=False
        )

    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("visit_seq", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_column("visit_seq")

    with op.batch_alter_table("sim_refunds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sim_refunds_organization_id"))

    op.drop_table("sim_refunds")
    with op.batch_alter_table("sim_tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sim_tickets_organization_id"))

    op.drop_table("sim_tickets")
    with op.batch_alter_table("sim_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sim_orders_organization_id"))
        batch_op.drop_index(batch_op.f("ix_sim_orders_customer_id"))

    op.drop_table("sim_orders")
    with op.batch_alter_table("tool_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_installations_organization_id"))

    op.drop_table("tool_installations")
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_calls_organization_id"))
        batch_op.drop_index("ix_tool_calls_org_created")
        batch_op.drop_index("ix_tool_calls_execution")

    op.drop_table("tool_calls")
    with op.batch_alter_table("sim_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sim_messages_organization_id"))

    op.drop_table("sim_messages")
    with op.batch_alter_table("sim_customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sim_customers_organization_id"))

    op.drop_table("sim_customers")
    # ### end Alembic commands ###
