"""Knowledge bases, documents (durable ingestion jobs), chunks with pgvector embeddings.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 17:38:05.387178
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import solutionforge.db.base

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    pg = op.get_bind().dialect.name == "postgresql"
    if pg:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("embedder", sa.String(length=64), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_knowledge_bases_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_bases_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_knowledge_bases_organization_id_name")
        ),
    )
    with op.batch_alter_table("knowledge_bases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_bases_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_uri", sa.String(length=2000), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ingesting",
                "ready",
                "failed",
                name="document_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.Column(
            "next_attempt_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column(
            "lease_expires_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("ingested_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_documents_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_documents_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "knowledge_base_id",
            "content_hash",
            name=op.f("uq_documents_knowledge_base_id_content_hash"),
        ),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_documents_claim", ["status", "next_attempt_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_documents_knowledge_base_id"), ["knowledge_base_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "chunks",
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=300), nullable=True),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("embedding", solutionforge.db.base.Embedding(dim=1024), nullable=False),
        sa.Column("created_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_chunks_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_chunks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name=op.f("uq_chunks_document_id_ordinal")),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chunks_document_id"), ["document_id"], unique=False)
        batch_op.create_index("ix_chunks_kb", ["knowledge_base_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_chunks_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###

    if pg:
        # PostgreSQL-only indexes (prefix pgx_ = ignored by the drift check).
        # HNSW for approximate nearest-neighbour search on cosine distance.
        op.execute(
            "CREATE INDEX pgx_chunks_embedding_hnsw ON chunks "
            "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
        )
        # Expression index matching the keyword query exactly, so the planner can use it.
        op.execute(
            "CREATE INDEX pgx_chunks_text_fts ON chunks USING gin (to_tsvector('english', text))"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS pgx_chunks_text_fts")
        op.execute("DROP INDEX IF EXISTS pgx_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_organization_id"))
        batch_op.drop_index("ix_chunks_kb")
        batch_op.drop_index(batch_op.f("ix_chunks_document_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_organization_id"))
        batch_op.drop_index(batch_op.f("ix_documents_knowledge_base_id"))
        batch_op.drop_index("ix_documents_claim")

    op.drop_table("documents")
    with op.batch_alter_table("knowledge_bases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_bases_organization_id"))

    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###
