"""Per-organization tool policy.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 18:02:18.987375
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import solutionforge.db.base

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_policies",
        sa.Column(
            "tool_policy", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", solutionforge.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_org_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_org_policies_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_policies")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_org_policies_organization_id")),
    )
    with op.batch_alter_table("org_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_org_policies_organization_id"), ["organization_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("org_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_policies_organization_id"))

    op.drop_table("org_policies")
    # ### end Alembic commands ###
