"""W3C traceparent on executions so worker spans continue the creating request's trace.

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-01 19:33:51.641298
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("traceparent", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_column("traceparent")

    # ### end Alembic commands ###
